fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "lou.bege@epsi.fr"
        sender_name: "lou.bege@epsi.fr"
    registration:
        form:
            type: App\Form\RegistrationType